sdkversion: 5.5.2
name: MAT-Asset-Suite
#name: TABLET_SABLE_MAT_DEV
capabilities:
- camera
- gps
- phone
version: 1.1.0
vendor: SABLE Data Works (Pty Ltd)
build: debug
applog: rholog.txt
android:
  version: 6.0
  abis: [arm, x86]
  extensions: ["gmaps"]
  emulator: GalaxyTab4_API_23
# Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  capabilities:
  - network_state
  - sdcard
  android_title: 0
  abis:
    - x86
    - arm
wp8:
  productid: "f61f1e30-8d41-0134-eaec-28d244c44896"
win32:
  deployqt: 1
  deploymsvc: 1
extensions:
- json
- rhoconnect-client
- rhoxml
- fileutils
- rholang
rhobundle:
  exclude_items:
  - thumb.db
#sdk: /home/sable/.rvm/gems/ruby-1.9.3-p551/gems/rhodes-5.5.0
